name: CI
on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - run: flutter pub get
      - run: bash tools/check_codegen_clean.sh
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart analyze --fatal-infos --fatal-warnings
      - run: flutter test --coverage

